## <font color = Brown> MCQs

### <font color =blue> Index of 50th element
Consider an (8, 8) shape NumPy array. What is the index (x,y) of the 50th element?

Note: For counting the elements go row-wise. For example, in the array,

[[1, 5, 9],

 [3, 0, 2]]

the 5th element would be '0'.

In [20]:
#create an 8*8 arr
arr = np.array(range(1,8*8+1))

#reshape it
arr = arr.reshape(8,8)

#find pos of 50
np.where(arr == 50)

(array([6], dtype=int64), array([1], dtype=int64))

In [21]:
arr.unravel_index(49, (8,8))

AttributeError: 'numpy.ndarray' object has no attribute 'unravel_index'

### <font color=blue> Slicing Arrays
Which of the following would extract all the first 3 rows of the last 5 columns in a given numpy 2D array ‘a’?

In [23]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [24]:
arr[:3,-5:]

array([[ 4,  5,  6,  7,  8],
       [12, 13, 14, 15, 16],
       [20, 21, 22, 23, 24]])

### <font color =blue>So Many Functions
What will the output of np.arange(1,16,2).reshape(4, 2) be?

In [25]:
np.arange(1,16,2).reshape(4, 2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

### <font color =red> Print "+"
Description
Given a single positive odd integer 'n' greater than 2, create a NumPy array of size (n x n) with all zeros and ones such that the ones make a shape like '+'. The lines of the plus must be present at the middle row and column.



Hint: Start by creating a (n x n) array with all zeroes using the np.zeros() function and then fill in the ones at the appropriate indices. Use integer division (//) to access the middle rows and columns



Examples:

Input 1:

3

Output 1:

[[0 1 0]

 [1 1 1]

 [0 1 0]]

Input 2:

5

Output 1:

[[0 0 1 0 0]

 [0 0 1 0 0]

 [1 1 1 1 1]

 [0 0 1 0 0]

 [0 0 1 0 0]]



Explanation: Notice that the 1s in the arrays make a shape like '+'.

In [14]:
# Read the input
n = int(input())

# Import the NumPy package
import numpy as np 

# Write your code here

#create a n*n zero array
arr = np.zeros((n,n), dtype = int)

mid = int((n-1)/2)

#assign 1 on middle row
arr[mid,:] = 1

#assign 1 on middle column
arr[:,mid] = 1

print(arr)

9
[[0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]]
